# Generated by Django 4.1.1 on 2022-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_id', models.CharField(max_length=150, verbose_name='Venta ID')),
                ('date', models.DateField(verbose_name='Fecha Venta')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('image', models.ImageField(upload_to='media', verbose_name='Imagen Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
                'ordering': ['id'],
            },
        ),
    ]
