# Generated by Django 4.1.1 on 2022-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0002_product_image'),
        ('GestionVentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='product',
            field=models.ManyToManyField(to='GestionProductos.product', verbose_name='Product'),
        ),
    ]
