# Generated by Django 4.1.1 on 2022-09-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVentas', '0002_venta_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='image',
            new_name='image1',
        ),
    ]
