# Generated by Django 4.1.1 on 2022-09-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVentas', '0003_rename_image_venta_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='image1',
            new_name='image',
        ),
    ]
