# Generated by Django 4.1.1 on 2022-09-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0002_product_image'),
        ('GestionVentas', '0004_rename_image1_venta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='product',
            field=models.ManyToManyField(to='GestionProductos.product'),
        ),
    ]
