# Generated by Django 4.1.1 on 2022-10-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=180, verbose_name='Correo electronico')),
                ('request_subject', models.CharField(max_length=16000, verbose_name='Asunto de la solicitud')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
                'ordering': ['id'],
            },
        ),
    ]
